// Generated by `bun init`. Trimmed to the one ambient module declaration
// this project actually uses — plain `.css` imports (see index.css). The
// scaffold also generates declarations for `*.svg` and `*.module.css`,
// but nothing here imports an SVG or uses CSS Modules.

declare module "*.css" {}
